cout<<"------------------------------------------------CAC LUA CHON DE QUAN LI-------------------------------------------------\n\n";
		// cout<<"\t\t\t\t\t0.lay tu thong tin va diem hoc sinh tu file"<<endl;
		// cout<<"\t\t\t\t\t1.nhap thong tin hoc sinh"<<endl;
		// cout<<"\t\t\t\t\t2.nhap diem cua hoc sinh"<<endl;
		// cout<<"\t\t\t\t\t3.hien thi thong tin cua hoc sinh"<<endl;
		// cout<<"\t\t\t\t\t4.hien thi diem cua hoc sinh"<<endl;
		// cout<<"\t\t\t\t\t5.hien thi thong tin va diem cua hoc sinh"<<endl;
		// cout<<"\t\t\t\t\t6.them hoc sinh vao dau danh sach lop hoc"<<endl;
		// cout<<"\t\t\t\t\t7.them hoc sinh vao cuoi danh sach lop hoc"<<endl;
		// cout<<"\t\t\t\t\t8.them hoc sinh vao vi tri bat ki trong danh sach lop hoc"<<endl;
		// cout<<"\t\t\t\t\t9.xoa hoc sinh o dau danh sach lop hoc"<<endl;
		// cout<<"\t\t\t\t\t10.xoa hoc sinh o cuoi danh sach lop hoc"<<endl;
		// cout<<"\t\t\t\t\t11.xoa hoc sinh o vi tri bat ki "<<endl;
		// cout<<"\t\t\t\t\t12.sua diem cho hoc sinh"<<endl;
		// cout<<"\t\t\t\t\t13.tim kiem hoc sinh"<<endl;
		// cout<<"\t\t\t\t\t14.sap xep diem"<<endl;
		// cout<<"\t\t\t\t\t15.hien thi thong tin va diem cua hoc sinh toan lop"<<endl;
		// cout<<"\t\t\t\t\nnhap TH:"; cin>>n;